
.ifndef IRQ0
.weak IRQ0
IRQ0:
		uret
.endif


.ifndef IRQ1
.weak IRQ1
IRQ1:
		uret
.endif


.ifndef IRQ2
.weak IRQ2
IRQ2:
		uret
.endif


.ifndef IRQ3
.weak IRQ3
IRQ3:
		uret
.endif


.ifndef IRQ4
.weak IRQ4
IRQ4:
		uret
.endif


.ifndef IRQ5
.weak IRQ5
IRQ5:
		uret
.endif


.ifndef IRQ6
.weak IRQ6
IRQ6:
		uret
.endif


.ifndef IRQ7
.weak IRQ7
IRQ7:
		uret
.endif


.ifndef IRQ8
.weak IRQ8
IRQ8:
		uret
.endif


.ifndef IRQ9
.weak IRQ9
IRQ9:
		uret
.endif


.ifndef IRQ10
.weak IRQ10
IRQ10:
		uret
.endif


.ifndef IRQ11
.weak IRQ11
IRQ11:
		uret
.endif


.ifndef IRQ12
.weak IRQ12
IRQ12:
		uret
.endif


.ifndef IRQ13
.weak IRQ13
IRQ13:
		uret
.endif


.ifndef IRQ14
.weak IRQ14
IRQ14:
		uret
.endif


.ifndef IRQ15
.weak IRQ15
IRQ15:
		uret
.endif

